<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\DecidedlyShared\DecidedlyShared.projitems" Label="Shared"/>

    <PropertyGroup>
        <Name>Magical Crops</Name>
        <Description>Plant (almost) anything.</Description>
        <MinimumApiVersion>4.3.2</MinimumApiVersion>
        <UpdateKeys>Nexus:00000</UpdateKeys>
        <Version>1.0.0-alpha</Version>
    </PropertyGroup>

    <PropertyGroup>
        <EnableHarmony>true</EnableHarmony>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug' ">
        <ContentPacks Include="packs\[CP] Magical Crops Content" Version="1.0.0-alpha" />
    </ItemGroup>

</Project>
